### ISSUE TITLE
center title over chart area

### ISSUE THREAD

**Issue by altsheets** [jaraco/svg.charts#10]
IMHO it looks a bit better if the title is centered over the chart area, not centered within the whole area.

Like this:

    class VerticalBar2(svg.charts.bar.VerticalBar):
        ...
        def draw_graph_title(self):
             text = etree.SubElement(self.root, 'text', {
                 'x': str( self.border_left/2 + self.width/2 ),
                 ...

 self.border_left/2 + self.width/2 == self.border_left+(self.width-self.border_left) / 2

**Comment by jaraco** [comment]
Can you provide an example of the before and after images so I can see what you mean?

**Comment by jaraco** [comment]
Please provide a PR.

**Comment by altsheets** [comment]
example: http://www.newbium.com/markets/wob-totals-BTC-ETH.svg
