### ISSUE TITLE
svg.charts.graph.burn --> self.draw_user_added_elements()

### ISSUE THREAD

**Issue by altsheets** [jaraco/svg.charts#12]
Last wish for today: 

Include one -initially empty- function into ``svg.charts.graph.burn()``:

    	def burn(self):
    	    ...   
    	    self.draw_data()
    	    ...
    	    self.draw_user_added_elements(self)

and ``self.draw_user_added_elements(parent)`` then allows me to stamp e.g. a tiny link, or timestamp, or copyright notice, ... into the SVG, before it is written to file.

Thanks again. I am almost done. When I have finalized my code, I'll probably share the combined ideas as a gist. 

Have a great day!

**Comment by jaraco** [comment]
You can do this today:

```python
class MyGraph(Graph):
    def draw_data(self):
        super(MyGraph, self).draw_data()
        self.draw_user_added_elements()

    def draw_user_added_elements(self):
        "stubbed; implement me"
```

Since you probably want this behavior to apply to other subclasses, you could implement it as a Mix-in:

```
class UserAdded(object):
    def draw_data(self):
        super(UserAdded, self).draw_data()
        self.draw_user_added_elements()

    def draw_user_added_elements(self):
        "stubbed; implement me"

class VerticalBar(UserAdded, svg.charts.bar.VerticalBar):
    "A UserAdded version of VerticalBar"
```

However, that gets to be a little tedious, so it doesn't seem unreasonable to provide a hook.

**Comment by altsheets** [comment]
Ah ... (slapping my forehead) ... of course - for that I can also recycle one of the existing subroutines that are called inside ``burn``. Good idea, I'll keep that mind for the future. 

I ended up with code similar to this one:

    def dataInfo_just_some_footnote_text(SELF):              
        "Just some workaround, quick'n'dirty hack."
            print "entered user defined routine; self=", SELF
            y = SELF.height
            text = etree.SubElement(SELF.root, 'text', {
                    'x': str(SELF.border_left/2 + SELF.width / 2),
                    'y': str(y),
                    'class': 'footnote'})
            text.text = SELF.footnote

After inserting the above hook

        self.draw_user_added_elements(self)

into ``burn``.

Yes, the SELF instead of ``self`` is weird, I know. But I wanted to somehow access the parent element's methods and attributes. And I hadn't used Mix-ins yet. Thanks for teaaching me this elegant way. And no, I don't find it tedious. And yes, it is good to design it in a way that can be easily added to other subclasses too. Cool, thx.

> it doesn't seem unreasonable to provide a hook

Yes :-)

**Comment by jaraco** [comment]
After some consideration, I realized that having the hooks in the Graph class itself just adds more complexity to the Graph implementation. And, since any implementation is going to need to create a custom subclass to implement the hooks, it's a small step to include a mix-in. Now, svg.charts.graph provides a mix-in class which can be readily used for this purpose.

Plus, since the functionality is in a separate class, it's very easy to see which hooks are defined, that their default implementation is empty, and how to define them. This feature will be in the 3.3 release shortly.

**Comment by jaraco** [comment]
> Yes, the SELF instead of self is weird, I know. But I wanted to somehow access the parent element's methods and attributes. 

I'm not sure I understand what you're expecting here. In Python, there's nothing special about the name `self`. It's just a convention... but whenever you have `self` (or any first parameter to an instance method), it will always be a reference to the instance of that class. From that, you can access the instance's methods or (using `super`) access the parent's methods.

I hope the example in the docstring helps you with your implementation.

**Comment by altsheets** [comment]
Thanks a lot. All very very helpful. 

> Now, svg.charts.graph provides a mix-in class which can be readily used for this purpose
Perfect. 

> helps you with your implementation
Oh, I was done with that, yesterday. My code is already working like a charm.

Thanks a lot!
