### ISSUE TITLE
Subclassing Line causes infinite recursion abort

### ISSUE THREAD

**Issue by sndgeek** [jaraco/svg.charts#17]
While trying the workaround for Issue #3 , I subclassed Line and implemented the start of an override for get_stylesheet().

	def get_stylesheet( self ):
		ss = super( PerfLine, self ).get_stylesheet()
                ...

Unfortunately, this code in Line.py makes any further usage crash:

	def calculate_left_margin(self):
		super(self.__class__, self).calculate_left_margin()
		label_left = len(self.fields[0]) / 2 * self.font_size * 0.6
		self.border_left = max(label_left, self.border_left)

b/c self.__class__ is now my subclass so this method ends up calling itself until it aborts via stack recursion hell.

Seems to work fine if I change it to "super(Line, self).calculate_left_margin()".

**Comment by jaraco** [comment]
Fixed in 3.4.4.
