### ISSUE TITLE
scale_y_integers / scale_x_integers doesn't work

### ISSUE THREAD

**Issue by chconnor** [jaraco/svg.charts#30]
Hi -- at least for a time_series, the settings scale_?_integers don't seem to work?

[Judging by the code](https://github.com/jaraco/svg.charts/blob/dea48d89d4fc562a24d406151472c6c1d904f3bc/svg/charts/plot.py#L238), they seem to only adjust the spacing of the axis labels, and don't actually make them integers, which seems to contradict the documentation [here](https://github.com/jaraco/svg.charts/blob/dea48d89d4fc562a24d406151472c6c1d904f3bc/svg/charts/plot.py#L101): "Make the Y axis labels integers".

I modified the beginning of the  data_range function like this:
```
    def data_range(self, axis):

        min_value = self.data_min(axis)
        max_value = self.data_max(axis)
        if getattr(self, 'scale_%s_integers' % axis):
            min_value = math.floor(min_value)
            max_value = math.ceil(max_value)
```
(with an `import math` at the top) and that makes the labels integers (assuming the scale_?_divisions is also an integer)

**Comment by jaraco** [comment]
Thanks. I've added it to v7.3.1. Let me know if that works for you.

**Comment by jaraco** [comment]
Well shoot. Adding that function broke the build. I see now you suggested modified the function, not adding it to the time series. Let me try that instead.
