### ISSUE TITLE
graph_subtitle(self) is printing self.graph_title

### ISSUE THREAD

**Issue by altsheets** [jaraco/svg.charts#8]
svg.charts.graph
    ...
    def draw_graph_subtitle(self):
    ...		
        text.text = self.graph_title

--> 

        text.text = self.graph_subtitle

additionally, can you please add a configurable offset between title and subtitle (at the moment it seems to be constant 10).

Thanks.

**Comment by jaraco** [comment]
> additionally, can you please add a configurable offset between title and subtitle (at the moment it seems to be constant 10).

Would you file this as a separate ticket please?
