### ISSUE TITLE
.each_different for increasing colors

### ISSUE THREAD

**Issue by altsheets** [jaraco/svg.charts#9]
I need a two colums VerticalBar but both columns need to have 2 different colors.

My suggestion:

    class VerticalBar2(svg.charts.bar.VerticalBar):
        def draw_data(self):
            ...
            for field_count, _ in enumerate(self.fields):
            for dataset_count, dataset in enumerate(self.data):
                ...
                _ = etree.SubElement(self.graph, 'rect', {
                    ...
                    'class': 'fill%s' % (1+dataset_count+(field_count if self.each_different else 0)*len(self.data)),

    g=VerticalBar2(["bids", "asks"])
    g.add_data({'data': [2, 3]})
    g.each_different=True

then each column gets a different color. 

Of course the color legend has to be switched off then. 

    g.key=False

**Comment by jaraco** [comment]
I'd like to avoid boolean settings that tweak functionality deep. Rather, what I'd like to do is extract a method for calculating the fill color.

**Comment by altsheets** [comment]
Fantastic. I like that solution. Maximum flexibility. 

Idea: You could actually even allow to make it dependent on the ``value``

    def _fill_class(self, dataset_index, field_index, value)

Then users could e.g. let the bar with the maximum (or minimum or most average) value ... stick out by color too. But ... that is a really esoteric case :-) Not needed by me right now, anyways.

Thanks a lot, for the quick solution.
